FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY JobQueue.Worker/JobQueue.Worker.csproj JobQueue.Worker/
COPY JobQueue.Application/JobQueue.Application.csproj JobQueue.Application/
COPY JobQueue.Domain/JobQueue.Domain.csproj JobQueue.Domain/
COPY JobQueue.Infrastructure/JobQueue.Infrastructure.csproj JobQueue.Infrastructure/

RUN dotnet restore JobQueue.Worker/JobQueue.Worker.csproj

COPY . .
WORKDIR /src/JobQueue.Worker
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "JobQueue.Worker.dll"]
